menu:
  Home: /
  Archives: /archives
  About: /about
sidebar: right

widgets:
- search
- category
- recent_posts
- tag
- tagcloud

# Duoshuo
# duoshuo_shortname: 

# disqus
disqus: blog-lungern-site

fancybox: true

google_analytics: UA-111754848-1
# rss: 
# google_site_verification: 
# baidu_site_verification: 
# icon: 